/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import static demo.Registracija.currentId;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import javax.swing.ImageIcon;

/**
 *
 * @author Domen
 */
public class Login extends javax.swing.JFrame {

    String username;
    String password;
    String[] profileParts;
    String userProfile;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setTitle("Login");
        ImageIcon img = new ImageIcon("src/slike/PerfectCookie (1).png");
        this.setIconImage(img.getImage());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        tfUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        back = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(780, 540));
        setMinimumSize(new java.awt.Dimension(780, 540));
        setPreferredSize(new java.awt.Dimension(780, 540));
        setResizable(false);
        setSize(new java.awt.Dimension(780, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 110, -1));

        jLabel2.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 270, -1, -1));

        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });
        getContentPane().add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 370, 110, -1));

        jLabel3.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 340, -1, -1));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/submit.png"))); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitMousePressed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/back.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/login.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-80, -40, 960, 630));

        setSize(new java.awt.Dimension(796, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassActionPerformed

    private void submitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMousePressed
        getData();
        if (checkUserProfile(username, password)) {
            userProfile = loadUserProfile(username, password);
            profileParts = userProfile.split("#");
            currentId = Integer.parseInt(profileParts[0]);
            new Okno1().setVisible(true);
            dispose();
        } else {
            jOptionPane1.showMessageDialog(null, "Incorrect username or password!");
            tfPass.setText(null);
        }
    }//GEN-LAST:event_submitMousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        new UvodnaStran().setVisible(true);
        dispose();
    }//GEN-LAST:event_backMousePressed

    /**
     * @param args the command line arguments
     */
    public void getData() {

        if (!tfUser.getText().equals("") && !new String(tfPass.getPassword()).equals("")) {
            username = tfUser.getText();
            password = getMd5(new String(tfPass.getPassword()));
        } else {
            jOptionPane1.showMessageDialog(null, "Incorrect username or password!");
        }
    }

    public String getMd5(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    public String loadUserProfile(String username, String password) {
        String userProfile = null;

        try (BufferedReader br = new BufferedReader(new FileReader("UserData.txt"))) {
            String line;

            while ((line = br.readLine()) != null) {
                String[] parts = line.split("#");

                if (parts.length > 3 && parts[1].equals(username) && parts[2].equals(password)) {
                    userProfile = line;
                    break;
                }
            }
            br.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return userProfile;
    }

    public boolean checkUserProfile(String username, String password) {
        boolean f = false;
        String userProfile = null;

        try (BufferedReader br = new BufferedReader(new FileReader("UserData.txt"))) {
            String line;

            while ((line = br.readLine()) != null) {
                String[] parts = line.split("#");

                if (parts.length > 3 && parts[1].equals(username) && parts[2].equals(password)) {
                    userProfile = line;
                    break;
                }
            }
            br.close();
            if (userProfile != null) {
                loadUserProfile(username, password);
                f = true;
            }
            
        } catch (IOException e) {
            e.printStackTrace();
        }
        return f;
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JLabel submit;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JTextField tfUser;
    // End of variables declaration//GEN-END:variables
}
