/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.awt.Desktop;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Arrays;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ThreadLocalRandom;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileView;

/**
 *
 * @author Domen
 */
public class Registracija extends javax.swing.JFrame {

    public static int userId;
    public static int currentId;
    String vUser;
    public static String vPass;
    String vPass2;
    String vPhone;
    String vName;
    String vName2;
    String vMail;
    String vGender;
    String vZIP;
    String vCountry;
    String vAddress;
    String vCity;
    String vDate;
    String vJob;
    String vPFP;
    private String temp;
    File pfp = new File("slike/default.jpg");
    boolean stop = false;

    /**
     * Creates new form Registracija
     */
    public Registracija() {
        initComponents();
        pfpl2.setHorizontalAlignment(SwingConstants.CENTER);
        this.setTitle("Registration");
        ImageIcon img = new ImageIcon("src/slike/PerfectCookie (1).png");
        this.setIconImage(img.getImage());
        jFrame1.setVisible(false);
        jFrame1.setLocationRelativeTo(null);
        jFrame1.setTitle("Username chooser wizard");
        ImageIcon img2 = new ImageIcon("src/slike/wizard.png");
        jFrame1.setIconImage(img2.getImage());
        jOptionPane1.setVisible(false);
        pfp1.setSelected(true);
        countries();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel24 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        tfUsernameChange = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        submitUsername = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        tfJob = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfUser = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfPass = new javax.swing.JPasswordField();
        tfPass2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfName = new javax.swing.JTextField();
        tfName2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfMail = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tfAddress = new javax.swing.JTextField();
        tfCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfZIP = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cbGender = new javax.swing.JComboBox<>();
        tfPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbCountry = new javax.swing.JComboBox<>();
        pfp6 = new javax.swing.JRadioButton();
        pfpl6 = new javax.swing.JLabel();
        pfp5 = new javax.swing.JRadioButton();
        pfpl5 = new javax.swing.JLabel();
        pfpl4 = new javax.swing.JLabel();
        pfp4 = new javax.swing.JRadioButton();
        pfp3 = new javax.swing.JRadioButton();
        pfpl3 = new javax.swing.JLabel();
        pfpl2 = new javax.swing.JLabel();
        pfp2 = new javax.swing.JRadioButton();
        pfp1 = new javax.swing.JRadioButton();
        pfpl1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        back = new javax.swing.JLabel();
        reset = new javax.swing.JLabel();
        submit = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jOptionPane1 = new javax.swing.JOptionPane();
        background = new javax.swing.JLabel();

        jFrame1.setAlwaysOnTop(true);
        jFrame1.setLocation(new java.awt.Point(0, 0));
        jFrame1.setLocationByPlatform(true);
        jFrame1.setMinimumSize(new java.awt.Dimension(400, 300));
        jFrame1.setSize(new java.awt.Dimension(400, 300));
        jFrame1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel24.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 204, 204));
        jFrame1.getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 300, 20));

        jLabel29.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("ENTER THE USERNAME OR SELECT ONE BELOW");
        jFrame1.getContentPane().add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        tfUsernameChange.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfUsernameChangeFocusGained(evt);
            }
        });
        tfUsernameChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfUsernameChangeActionPerformed(evt);
            }
        });
        tfUsernameChange.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfUsernameChangeKeyTyped(evt);
            }
        });
        jFrame1.getContentPane().add(tfUsernameChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 240, -1));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText("jRadioButton1");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 150, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText("jRadioButton1");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 150, -1));

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText("jRadioButton1");
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jRadioButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 150, -1));

        submitUsername.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/submit.png"))); // NOI18N
        submitUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitUsernameMouseClicked(evt);
            }
        });
        jFrame1.getContentPane().add(submitUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 196, 80));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/game.png"))); // NOI18N
        jFrame1.getContentPane().add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(-250, -190, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 780, 540));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximumSize(new java.awt.Dimension(780, 540));
        setMinimumSize(new java.awt.Dimension(780, 540));
        setPreferredSize(new java.awt.Dimension(780, 540));
        setResizable(false);
        setSize(new java.awt.Dimension(780, 540));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(tfJob, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 180, -1));

        jLabel27.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Job title");
        getContentPane().add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, -1, -1));

        jLabel1.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));
        getContentPane().add(tfUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 110, -1));

        jLabel2.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 30, -1, -1));

        tfPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPassActionPerformed(evt);
            }
        });
        getContentPane().add(tfPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 110, -1));
        getContentPane().add(tfPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 110, -1));

        jLabel3.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Confirm password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, -1, -1));

        jLabel4.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));
        getContentPane().add(tfName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 110, -1));
        getContentPane().add(tfName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 110, -1));

        jLabel5.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Last name");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, -1, -1));
        getContentPane().add(tfMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 180, -1));

        jLabel6.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Email");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 110, -1, -1));

        jLabel7.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, -1, -1));

        jLabel8.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Address");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 190, -1, -1));

        jLabel23.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Profile picture");
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));
        getContentPane().add(tfAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 140, -1));
        getContentPane().add(tfCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 220, 110, -1));

        jLabel9.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("City");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 190, -1, -1));

        jLabel10.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("ZIP");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, -1, -1));
        getContentPane().add(tfZIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 80, -1));

        jLabel11.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Birthdate");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        cbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select", "Male", "Female", "Rather not say" }));
        cbGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGenderActionPerformed(evt);
            }
        });
        getContentPane().add(cbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, -1, -1));
        getContentPane().add(tfPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 110, -1));

        jLabel12.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 0, 0));
        jLabel12.setText("*");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        cbCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCountryActionPerformed(evt);
            }
        });
        getContentPane().add(cbCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 190, -1));

        buttonGroup2.add(pfp6);
        getContentPane().add(pfp6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        pfpl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/p4.png"))); // NOI18N
        pfpl6.setLabelFor(pfp6);
        pfpl6.setToolTipText("");
        pfpl6.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pfpl6.setMaximumSize(new java.awt.Dimension(24, 24));
        pfpl6.setMinimumSize(new java.awt.Dimension(24, 24));
        pfpl6.setPreferredSize(new java.awt.Dimension(24, 24));
        pfpl6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfpl6MouseClicked(evt);
            }
        });
        getContentPane().add(pfpl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 40, 40));

        buttonGroup2.add(pfp5);
        getContentPane().add(pfp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 310, -1, -1));

        pfpl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/p3.png"))); // NOI18N
        pfpl5.setLabelFor(pfp5);
        pfpl5.setToolTipText("");
        pfpl5.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pfpl5.setMaximumSize(new java.awt.Dimension(24, 24));
        pfpl5.setMinimumSize(new java.awt.Dimension(24, 24));
        pfpl5.setPreferredSize(new java.awt.Dimension(24, 24));
        pfpl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfpl5MouseClicked(evt);
            }
        });
        getContentPane().add(pfpl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 300, 40, 40));

        pfpl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/p2.png"))); // NOI18N
        pfpl4.setLabelFor(pfp4);
        pfpl4.setToolTipText("");
        pfpl4.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pfpl4.setMaximumSize(new java.awt.Dimension(24, 24));
        pfpl4.setMinimumSize(new java.awt.Dimension(24, 24));
        pfpl4.setPreferredSize(new java.awt.Dimension(24, 24));
        pfpl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfpl4MouseClicked(evt);
            }
        });
        getContentPane().add(pfpl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 350, 40, 40));

        buttonGroup2.add(pfp4);
        getContentPane().add(pfp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 360, -1, -1));

        buttonGroup2.add(pfp3);
        getContentPane().add(pfp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 310, -1, -1));

        pfpl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/p1.png"))); // NOI18N
        pfpl3.setLabelFor(pfp3);
        pfpl3.setToolTipText("");
        pfpl3.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pfpl3.setMaximumSize(new java.awt.Dimension(24, 24));
        pfpl3.setMinimumSize(new java.awt.Dimension(24, 24));
        pfpl3.setPreferredSize(new java.awt.Dimension(24, 24));
        pfpl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfpl3MouseClicked(evt);
            }
        });
        getContentPane().add(pfpl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 40, 40));

        pfpl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/izberi.png"))); // NOI18N
        pfpl2.setLabelFor(pfp2);
        pfpl2.setToolTipText("");
        pfpl2.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pfpl2.setMaximumSize(new java.awt.Dimension(24, 24));
        pfpl2.setMinimumSize(new java.awt.Dimension(24, 24));
        pfpl2.setPreferredSize(new java.awt.Dimension(24, 24));
        pfpl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfpl2MouseClicked(evt);
            }
        });
        getContentPane().add(pfpl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 300, 40, 40));

        buttonGroup2.add(pfp2);
        getContentPane().add(pfp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        buttonGroup2.add(pfp1);
        getContentPane().add(pfp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 360, -1, -1));

        pfpl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/default.png"))); // NOI18N
        pfpl1.setLabelFor(pfp1);
        pfpl1.setToolTipText("");
        pfpl1.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        pfpl1.setMaximumSize(new java.awt.Dimension(24, 24));
        pfpl1.setMinimumSize(new java.awt.Dimension(24, 24));
        pfpl1.setPreferredSize(new java.awt.Dimension(24, 24));
        pfpl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pfpl1MouseClicked(evt);
            }
        });
        getContentPane().add(pfpl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 40, 40));
        getContentPane().add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 170, -1));

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/back.png"))); // NOI18N
        back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                backMousePressed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, -1));

        reset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/reset.png"))); // NOI18N
        reset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resetMousePressed(evt);
            }
        });
        getContentPane().add(reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, -1, -1));

        submit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/submit.png"))); // NOI18N
        submit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                submitMousePressed(evt);
            }
        });
        getContentPane().add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, -1));

        jLabel13.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Phone");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 0, 0));
        jLabel14.setText("*");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jLabel15.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 0, 0));
        jLabel15.setText("*");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 180, -1, -1));

        jLabel16.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 0, 0));
        jLabel16.setText("*");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 0, 0));
        jLabel17.setText("*");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabel18.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 0, 0));
        jLabel18.setText("*");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, -1, -1));

        jLabel19.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 0, 0));
        jLabel19.setText("*");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, -1, -1));

        jLabel20.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 0, 0));
        jLabel20.setText("*");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));

        jLabel21.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setText("*");
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jLabel22.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 0, 0));
        jLabel22.setText("*");
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 20, -1, -1));

        jLabel25.setFont(new java.awt.Font("Burbank Big Rg Bk", 0, 36)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 0, 0));
        jLabel25.setText("*");
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, -1, -1));

        jLabel26.setFont(new java.awt.Font("Burbank Big Rg Bd", 0, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Country");
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        getContentPane().add(jOptionPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/game.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -48, 786, 642));

        setSize(new java.awt.Dimension(796, 548));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void cbGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbGenderActionPerformed

    private void cbCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCountryActionPerformed

    private void submitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitMousePressed
        getData();
        stop = false;
    }//GEN-LAST:event_submitMousePressed

    private void submitUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitUsernameMouseClicked
        boolean exists = false;
        String tempUser = "";
        try {
            BufferedReader br = new BufferedReader(new FileReader("UserData.txt"));
            String line;
            boolean s = false;

            // Read each line from the file
            while ((line = br.readLine()) != null && s == false) {
                // Split the line into parts using "#"
                String[] parts = line.split("#");
                if (parts[1].equals(tfUsernameChange.getText())) {
                    exists = true;
                    tempUser = tfUsernameChange.getText();
                    tfUsernameChange.setText("");
                    s = true;
                }

            }
            br.close();
        } catch (IOException e) {
            e.printStackTrace(); // Handle or log the exception appropriately
        }
        if (!tfUsernameChange.getText().equals("")) {
            vUser = tfUsernameChange.getText();
            tfUser.setText(vUser);
            jFrame1.setVisible(false);
            getData();
        } else if (jRadioButton1.isSelected()) {
            vUser = jRadioButton1.getText();
            tfUser.setText(vUser);
            jFrame1.setVisible(false);
            getData();
        } else if (jRadioButton2.isSelected()) {
            vUser = jRadioButton2.getText();
            tfUser.setText(vUser);
            jFrame1.setVisible(false);
            getData();
        } else if (jRadioButton3.isSelected()) {
            vUser = jRadioButton3.getText();
            tfUser.setText(vUser);
            jFrame1.setVisible(false);
            getData();
        } else if (tfUsernameChange.getText().equals("")) {
            if (exists) {
                jLabel24.setText("Username \'" + tempUser + "\' already exists!");
            } else {
                jLabel24.setText("Enter an username OR choose 1 from the menu!");
            }
        }
    }//GEN-LAST:event_submitUsernameMouseClicked

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        tfUsernameChange.setText(null);
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        tfUsernameChange.setText(null);
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        tfUsernameChange.setText(null);
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void tfUsernameChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfUsernameChangeActionPerformed

    }//GEN-LAST:event_tfUsernameChangeActionPerformed

    private void tfUsernameChangeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfUsernameChangeKeyTyped
        jRadioButton3.setSelected(false);
        jRadioButton1.setSelected(false);
        jRadioButton2.setSelected(false);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_tfUsernameChangeKeyTyped

    private void tfUsernameChangeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfUsernameChangeFocusGained

    }//GEN-LAST:event_tfUsernameChangeFocusGained

    private void tfPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPassActionPerformed

    private void resetMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resetMousePressed
        reset();
    }//GEN-LAST:event_resetMousePressed

    private void backMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backMousePressed
        new UvodnaStran().setVisible(true);
        dispose();
    }//GEN-LAST:event_backMousePressed

    private void pfpl2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfpl2MouseClicked
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Izberite sliko!");
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Images", "jpg", "png", "gif", "jpeg");
        fileChooser.setFileFilter(filter);
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            String[] fileName = selectedFile.getName().split("\\.");

            // Generate a random unique code
            String uniqueCode = UUID.randomUUID().toString().substring(0, 8); // Adjust length as needed

            // Append the unique code to the file name
            String fileNameWithCode = fileName[0] + "_" + uniqueCode + "." + fileName[1];
            vPFP = "slike/" + fileNameWithCode;

            try {
                BufferedImage originalImage = ImageIO.read(selectedFile);
                int originalWidth = originalImage.getWidth();
                int originalHeight = originalImage.getHeight();

                // Scale the image to fit within a 40x40px square
                int scaledWidth, scaledHeight;
                if (originalWidth > originalHeight) {
                    scaledWidth = 40;
                    scaledHeight = (int) (40.0 / originalWidth * originalHeight);
                } else {
                    scaledWidth = (int) (40.0 / originalHeight * originalWidth);
                    scaledHeight = 40;
                }

                Image scaledImage = originalImage.getScaledInstance(scaledWidth, scaledHeight, Image.SCALE_SMOOTH);
                ImageIcon scaledIcon = new ImageIcon(scaledImage);
                pfpl2.setIcon(scaledIcon);

                Path outputPath = Paths.get("slike/", fileNameWithCode);
                Files.copy(selectedFile.toPath(), outputPath);
                pfp2.setSelected(true);
                JOptionPane.showMessageDialog(rootPane, "Slika uspešno naložena!");
            } catch (IOException ex) {
                JOptionPane.showMessageDialog(this, "Napaka pri kopiranju slike, program se bo zaustavil.", "Napaka", JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
                dispose();
            }
        }
    }//GEN-LAST:event_pfpl2MouseClicked

    private void pfpl1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfpl1MouseClicked
        pfp1.setSelected(true);
    }//GEN-LAST:event_pfpl1MouseClicked

    private void pfpl3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfpl3MouseClicked
        pfp3.setSelected(true);
    }//GEN-LAST:event_pfpl3MouseClicked

    private void pfpl4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfpl4MouseClicked
        pfp4.setSelected(true);
    }//GEN-LAST:event_pfpl4MouseClicked

    private void pfpl5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfpl5MouseClicked
        pfp5.setSelected(true);
    }//GEN-LAST:event_pfpl5MouseClicked

    private void pfpl6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pfpl6MouseClicked
        pfp6.setSelected(true);
    }//GEN-LAST:event_pfpl6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registracija.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registracija().setVisible(true);
            }
        });
    }

    public void checkPhone() {
        String phoneNumber = tfPhone.getText();
        // Define the regex pattern
        String regex = "^0\\d{8}$";
        String regex2 = "^\\+[1-9]\\d{10}$";
        String regex3 = "^\\+[1-9]\\d{9}$";

        if (!phoneNumber.matches(regex) && !phoneNumber.matches(regex2) && !phoneNumber.matches(regex3)) {
            JOptionPane.showMessageDialog(null, "Enter a valid phone number or leave the field empty!");
            tfPhone.setText("");
            stop = true;
        } else {
            stop = false;
            vPhone = phoneNumber;
        }
    }

    public void countries() {

        String[] countries = {
            "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua and Barbuda", "Argentina", "Armenia",
            "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium",
            "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina", "Botswana", "Brazil", "Brunei",
            "Bulgaria", "Burkina Faso", "Burundi", "Cabo Verde", "Cambodia", "Cameroon", "Canada", "Central African Republic",
            "Chad", "Chile", "China", "Colombia", "Comoros", "Congo, Democratic Republic of the", "Congo, Republic of the",
            "Costa Rica", "Cote d'Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti",
            "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia",
            "Eswatini", "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Greece",
            "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Honduras", "Hungary", "Iceland", "India",
            "Indonesia", "Iran", "Iraq", "Ireland", "Israel", "Italy", "Jamaica", "Japan", "Jordan", "Kazakhstan", "Kenya",
            "Kiribati", "Korea, North", "Korea, South", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho",
            "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali",
            "Malta", "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia",
            "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia", "Nauru", "Nepal", "Netherlands", "New Zealand",
            "Nicaragua", "Niger", "Nigeria", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine", "Panama",
            "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland", "Portugal", "Qatar", "Romania", "Russia", "Rwanda",
            "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino", "Sao Tome and Principe",
            "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands",
            "Somalia", "South Africa", "South Sudan", "Spain", "Sri Lanka", "Sudan", "Suriname", "Sweden", "Switzerland", "Syria",
            "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
            "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States",
            "Uruguay", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe"
        };

        cbCountry.addItem("Select");
        for (String country : countries) {
            cbCountry.addItem(country);
        }

    }

    public void checkUsername() {
        try {
            // Open the file for reading
            BufferedReader br = new BufferedReader(new FileReader("UserData.txt"));
            String line;
            boolean s = false;

            // Read each line from the file
            while ((line = br.readLine()) != null && s == false) {
                // Split the line into parts using "#"
                String[] parts = line.split("#");
                if (parts[1].equals(tfUser.getText())) {
                    jOptionPane1.showMessageDialog(null, "Username \'" + tfUser.getText() + "\' already exists!");
                    jFrame1.setVisible(true);
                    username();
                    tfUser.setText(null);
                    s = true;
                } else {
                    vUser = tfUser.getText();
                }

            }
            br.close();
        } catch (IOException e) {
            e.printStackTrace(); // Handle or log the exception appropriately
        }
    }

    public void username() {
        int random = (int) (Math.random() * 899) + 100;
        jRadioButton1.setText(tfUser.getText() + random);
        random = (int) (Math.random() * 899) + 100;
        jRadioButton2.setText(tfName.getText() + tfName2.getText().charAt(0) + random);
        random = (int) (Math.random() * 899) + 100;
        jRadioButton3.setText(tfName2.getText() + tfName.getText().charAt(0) + random);
    }

    public String getMd5(String input) {
        try {
            MessageDigest md = MessageDigest.getInstance("MD5");
            byte[] messageDigest = md.digest(input.getBytes());
            BigInteger no = new BigInteger(1, messageDigest);
            String hashtext = no.toString(16);
            while (hashtext.length() < 32) {
                hashtext = "0" + hashtext;
            }
            return hashtext;
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException(e);
        }
    }

    public void reset() {
        tfUser.setText(null);
        tfPass.setText(null);
        tfPass2.setText(null);
        tfPhone.setText(null);
        tfName.setText(null);
        tfName2.setText(null);
        tfMail.setText(null);
        cbGender.setSelectedItem("Select");
        cbCountry.setSelectedItem("Select");
        tfZIP.setText(null);
        tfAddress.setText(null);
        tfCity.setText(null);
        tfJob.setText(null);
        pfp1.setSelected(true);
        jDateChooser1.setDate(null);
    }

    public boolean isValid(String email) {
        String emailRegex = "^[a-zA-Z0-9_+&*-]+(?:\\."
                + "[a-zA-Z0-9_+&*-]+)*@"
                + "(?:[a-zA-Z0-9-]+\\.)+[a-z"
                + "A-Z]{2,7}$";

        Pattern pat = Pattern.compile(emailRegex);
        if (email == null) {
            return false;
        }
        return pat.matcher(email).matches();
    }

    public void checkMail() {
        if (!isValid(tfMail.getText())) {
            jOptionPane1.showMessageDialog(null, "Enter a valid Email address!");
            tfMail.setText("");
        } else {
            vMail = tfMail.getText();
        }
    }

    public void getDate() {
        if (jDateChooser1.getDate() != null) {
            String[] date = jDateChooser1.getDate().toString().split(" ");
            vDate = date[2] + " " + date[1] + " " + date[5];
        } else {
            vDate = "";
        }
    }

    public void getPFP() {
        if (pfp1.isSelected()) {
            vPFP = "src/slike/default.png";
        } else if (pfp3.isSelected()) {
            vPFP = "src/slike/p1.png";
        } else if (pfp4.isSelected()) {
            vPFP = "src/slike/p2.png";
        } else if (pfp5.isSelected()) {
            vPFP = "src/slike/p3.png";
        } else if (pfp6.isSelected()) {
            vPFP = "src/slike/p4.png";
        }
    }

    public void checkZIP() {
        String zipCode = tfZIP.getText();
        // Define the regex pattern for a ZIP code
        String zipRegex = "^[1-9]\\d{3}$";

        if (!zipCode.matches(zipRegex)) {
            JOptionPane.showMessageDialog(null, "Enter a valid ZIP code!");
            tfZIP.setText("");
        } else {
            vZIP = zipCode;
        }
    }

    public void getData() {

        if (!tfUser.getText().equals("") && !new String(tfPass.getPassword()).equals("") && !tfName.getText().equals("") && !tfName2.getText().equals("") && !tfMail.getText().equals("") && !String.valueOf(cbGender.getSelectedItem()).equals("Select") && !String.valueOf(cbCountry.getSelectedItem()).equals("Select") && !tfZIP.getText().equals("") && !tfAddress.getText().equals("") && !tfCity.getText().equals("") && !stop) {
            checkUsername();
            if (!tfUser.getText().equals("")) {
                checkPassword();
            }
            vName = tfName.getText();
            vName2 = tfName2.getText();
            if (!new String(tfPass2.getPassword()).equals("") && !tfUser.getText().equals("")) {
                checkMail();
            }
            vGender = String.valueOf(cbGender.getSelectedItem());
            vCountry = String.valueOf(cbCountry.getSelectedItem());
            if (!new String(tfPass2.getPassword()).equals("") && !tfUser.getText().equals("") && !tfMail.getText().equals("")) {
                checkZIP();
            }
            if (!tfPhone.getText().equals("") && !new String(tfPass2.getPassword()).equals("") && !tfUser.getText().equals("") && !tfZIP.getText().equals("") && !tfMail.getText().equals("")) {
                checkPhone();
            } else {
                stop = false;
            }
            vAddress = tfAddress.getText();
            vCity = tfCity.getText();
            getDate();
            vJob = tfJob.getText();
            getPFP();
            if (!new String(tfPass.getPassword()).equals("") && !new String(tfPass2.getPassword()).equals("") && !tfUser.getText().equals("") && !tfMail.getText().equals("") && !tfZIP.getText().equals("") && !stop) {
                setData();
            }
        } else {
            jOptionPane1.showMessageDialog(null, "Mandatory fields (*) must not be empty!");
        }
    }

    public void checkPassword() {
        vPass = new String(tfPass.getPassword());
        int n = vPass.length();
        boolean hasLower = false;
        boolean hasUpper = false;
        boolean hasDigit = false;
        boolean specialChar = false;
        Set<Character> set = new HashSet<>(Arrays.asList('!', '@', '$', '%', '^', '&', '*', '(', ')', '-', '+'));
        for (char i : vPass.toCharArray()) {
            if (Character.isLowerCase(i)) {
                hasLower = true;
            }
            if (Character.isUpperCase(i)) {
                hasUpper = true;
            }
            if (Character.isDigit(i)) {
                hasDigit = true;
            }
            if (set.contains(i)) {
                specialChar = true;
            }
        }
        if (hasDigit && hasLower && hasUpper && specialChar && (n >= 8)) {
            password();
        } else {
            jOptionPane1.showMessageDialog(null, "Password must meet complexity requirements: \nMinimum length: 8 \nLower case letter: 1 \nUpper case letter: 1 \nNumber: 1 \nSymbol: 1");
            tfPass.setText(null);
            tfPass2.setText(null);
        }
    }

    public void password() {
        if ((new String(tfPass.getPassword())).equals(new String(tfPass2.getPassword()))) {
            vPass = getMd5(new String(tfPass.getPassword()));
        } else {
            jOptionPane1.showMessageDialog(null, "Passwords do not match!");
            tfPass2.setText(null);
        }
    }

    public void setData() {
        try {
            File f = new File("UserData.txt");
            if (!f.exists()) {
                f.createNewFile();
            }
            BufferedReader br = new BufferedReader(new FileReader(f));
            Object Lines[] = br.lines().toArray();
            int id = 0;
            for (int i = 0; i < Lines.length; i++) {
                String Line = Lines[i].toString().trim();
                String[] Row = Line.split("#");
                id = Integer.parseInt(Row[0]);
            }
            br.close();
            userId = id + 1;
            currentId = id + 1;

            FileWriter fw = new FileWriter(f, true);
            BufferedWriter bw = new BufferedWriter(fw);
            PrintWriter pw2 = new PrintWriter(bw);
            pw2.println(userId + "#" + vUser + "#" + vPass + "#" + vName + "#" + vName2 + "#" + vMail + "#" + vPhone + "#" + vGender + "#" + vCountry + "#" + vAddress + "#" + vZIP + "#" + vCity + "#" + vDate + "#" + vJob + "#" + vPFP);
            pw2.flush();
            pw2.close();
            bw.close();
            fw.close();

            String filePath = "saves/" + vUser + ".txt";
            File u = new File(filePath);
            if (!u.exists()) {
                u.createNewFile();
            }
            PrintWriter pw = new PrintWriter(u);
            pw.println(0);
            pw.println(0);
            pw.println(0);
            pw.println(15);
            pw.println(0);
            pw.println(100);
            pw.println(0);
            pw.println(1100);
            pw.println(0);
            pw.println(12000);
            pw.println(0);
            pw.println(130000);
            pw.println(1);
            pw.println(1);
            pw.println(1);
            pw.println(1);
            pw.println(1);
            pw.println(1);
            pw.println(1);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(false);
            pw.println(0);
            fw.close();
            bw.close();
            pw.close();

            new Okno1().setVisible(true);
            dispose();

        } catch (IOException e) {
            e.printStackTrace(); // Handle or log the exception properly
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel back;
    private javax.swing.JLabel background;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cbCountry;
    private javax.swing.JComboBox<String> cbGender;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton pfp1;
    private javax.swing.JRadioButton pfp2;
    private javax.swing.JRadioButton pfp3;
    private javax.swing.JRadioButton pfp4;
    private javax.swing.JRadioButton pfp5;
    private javax.swing.JRadioButton pfp6;
    private javax.swing.JLabel pfpl1;
    private javax.swing.JLabel pfpl2;
    private javax.swing.JLabel pfpl3;
    private javax.swing.JLabel pfpl4;
    private javax.swing.JLabel pfpl5;
    private javax.swing.JLabel pfpl6;
    private javax.swing.JLabel reset;
    private javax.swing.JLabel submit;
    private javax.swing.JLabel submitUsername;
    private javax.swing.JTextField tfAddress;
    private javax.swing.JTextField tfCity;
    private javax.swing.JTextField tfJob;
    private javax.swing.JTextField tfMail;
    private javax.swing.JTextField tfName;
    private javax.swing.JTextField tfName2;
    private javax.swing.JPasswordField tfPass;
    private javax.swing.JPasswordField tfPass2;
    private javax.swing.JTextField tfPhone;
    private javax.swing.JTextField tfUser;
    private javax.swing.JTextField tfUsernameChange;
    private javax.swing.JTextField tfZIP;
    // End of variables declaration//GEN-END:variables
}
