/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import static demo.UvodnaStran.save;
import java.io.File;
import java.nio.file.Path;
import java.nio.file.Paths;

/**
 *
 * @author Voixy
 */
public class SaveFiles extends javax.swing.JFrame {

    public static String savefile1, savefile2, savefile3, savefile4, savefile5;
    public static File sf1, sf2, sf3, sf4, sf5;
    Path currentRelativePath = Paths.get("");
    public String pat = currentRelativePath.toAbsolutePath().toString();
    public File f = new File(pat+"\\saves");
    

    /**
     * Creates new form SaveFiles
     */
    public SaveFiles() {
        initComponents();
        bgcreatenew.setVisible(false);
        jLabel1.setVisible(false);
        createnew.setVisible(false);
        jTextField1.setVisible(false);
        jOptionPane1.setVisible(false);
        
        
        
        try {
        String ff[] = f.list();
        if (ff.length == 1) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        } else if (ff.length == 2) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        } else if (ff.length == 3) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        } else if (ff.length == 4) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText(ff[3]+"");
        savefile4 = ff[3]+"";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        } else if (ff.length == 5) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText(ff[3]+"");
        savefile4 = ff[3]+"";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        file5.setText(ff[4]+"");
        savefile5 = ff[4]+"";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        }
        } catch (NullPointerException e) {}
        
        if (file1.getText().equals("EMPTY SAVE")) {
            load1.setText("NEW");
        }
        if (file2.getText().equals("EMPTY SAVE")) {
            load2.setText("NEW");
        }
        if (file3.getText().equals("EMPTY SAVE")) {
            load3.setText("NEW");
        }
        if (file4.getText().equals("EMPTY SAVE")) {
            load4.setText("NEW");
        }
        if (file5.getText().equals("EMPTY SAVE")) {
            load5.setText("NEW");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jTextField1 = new javax.swing.JTextField();
        file1 = new javax.swing.JLabel();
        file2 = new javax.swing.JLabel();
        file3 = new javax.swing.JLabel();
        file4 = new javax.swing.JLabel();
        file5 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();
        bg5 = new javax.swing.JLabel();
        del1 = new javax.swing.JLabel();
        del2 = new javax.swing.JLabel();
        del3 = new javax.swing.JLabel();
        del4 = new javax.swing.JLabel();
        del5 = new javax.swing.JLabel();
        bgd1 = new javax.swing.JLabel();
        bgd2 = new javax.swing.JLabel();
        bgd3 = new javax.swing.JLabel();
        bgd4 = new javax.swing.JLabel();
        bg10 = new javax.swing.JLabel();
        load1 = new javax.swing.JLabel();
        load2 = new javax.swing.JLabel();
        load3 = new javax.swing.JLabel();
        load4 = new javax.swing.JLabel();
        load5 = new javax.swing.JLabel();
        bgl1 = new javax.swing.JLabel();
        bgl2 = new javax.swing.JLabel();
        bgl3 = new javax.swing.JLabel();
        bgl4 = new javax.swing.JLabel();
        bgl5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        createnew = new javax.swing.JLabel();
        bgcreatenew = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jOptionPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        jTextField1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 476, 208, 40));

        file1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file1.setForeground(new java.awt.Color(255, 255, 255));
        file1.setText("EMPTY SAVE");
        getContentPane().add(file1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 82, -1, -1));

        file2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file2.setForeground(new java.awt.Color(255, 255, 255));
        file2.setText("EMPTY SAVE");
        getContentPane().add(file2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 158, -1, -1));

        file3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file3.setForeground(new java.awt.Color(255, 255, 255));
        file3.setText("EMPTY SAVE");
        getContentPane().add(file3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        file4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file4.setForeground(new java.awt.Color(255, 255, 255));
        file4.setText("EMPTY SAVE");
        getContentPane().add(file4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 304, -1, -1));

        file5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file5.setForeground(new java.awt.Color(255, 255, 255));
        file5.setText("EMPTY SAVE");
        getContentPane().add(file5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 378, -1, -1));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 60, -1, -1));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 136, -1, -1));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 210, -1, -1));

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 282, -1, -1));

        bg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 356, -1, -1));

        del1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del1.setForeground(new java.awt.Color(255, 255, 255));
        del1.setText("DELETE");
        getContentPane().add(del1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 74, -1, -1));

        del2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del2.setForeground(new java.awt.Color(255, 255, 255));
        del2.setText("DELETE");
        getContentPane().add(del2, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 150, -1, -1));

        del3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del3.setForeground(new java.awt.Color(255, 255, 255));
        del3.setText("DELETE");
        getContentPane().add(del3, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 222, -1, -1));

        del4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del4.setForeground(new java.awt.Color(255, 255, 255));
        del4.setText("DELETE");
        getContentPane().add(del4, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 296, -1, -1));

        del5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del5.setForeground(new java.awt.Color(255, 255, 255));
        del5.setText("DELETE");
        getContentPane().add(del5, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 370, -1, -1));

        bgd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgd1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgd1MousePressed(evt);
            }
        });
        getContentPane().add(bgd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 52, -1, -1));

        bgd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgd2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgd2MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bgd2MouseReleased(evt);
            }
        });
        getContentPane().add(bgd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 128, -1, -1));

        bgd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgd3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgd3MousePressed(evt);
            }
        });
        getContentPane().add(bgd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 202, -1, -1));

        bgd4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgd4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgd4MousePressed(evt);
            }
        });
        getContentPane().add(bgd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 274, -1, -1));

        bg10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bg10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bg10MousePressed(evt);
            }
        });
        getContentPane().add(bg10, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 348, -1, -1));

        load1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load1.setForeground(new java.awt.Color(255, 255, 255));
        load1.setText("LOAD");
        getContentPane().add(load1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 82, -1, -1));

        load2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load2.setForeground(new java.awt.Color(255, 255, 255));
        load2.setText("LOAD");
        getContentPane().add(load2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 158, -1, -1));

        load3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load3.setForeground(new java.awt.Color(255, 255, 255));
        load3.setText("LOAD");
        getContentPane().add(load3, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 230, -1, -1));

        load4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load4.setForeground(new java.awt.Color(255, 255, 255));
        load4.setText("LOAD");
        getContentPane().add(load4, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 304, -1, -1));

        load5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load5.setForeground(new java.awt.Color(255, 255, 255));
        load5.setText("LOAD");
        getContentPane().add(load5, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 378, -1, -1));

        bgl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgl1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgl1MousePressed(evt);
            }
        });
        getContentPane().add(bgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 58, -1, -1));

        bgl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgl2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgl2MousePressed(evt);
            }
        });
        getContentPane().add(bgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 134, -1, -1));

        bgl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgl3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgl3MousePressed(evt);
            }
        });
        getContentPane().add(bgl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 208, -1, -1));

        bgl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgl4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgl4MousePressed(evt);
            }
        });
        getContentPane().add(bgl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 280, -1, -1));

        bgl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgl5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgl5MousePressed(evt);
            }
        });
        getContentPane().add(bgl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 354, -1, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel1.setText("ENTER SAVE FILE NAME:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 450, -1, -1));

        createnew.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        createnew.setForeground(new java.awt.Color(255, 255, 255));
        createnew.setText("CREATE");
        getContentPane().add(createnew, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 474, -1, -1));

        bgcreatenew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        bgcreatenew.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgcreatenewMousePressed(evt);
            }
        });
        getContentPane().add(bgcreatenew, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 452, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/game.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -48, 786, 642));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bgl1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgl1MousePressed
        save = new File(pat+"\\saves\\"+savefile1);
        new Okno1().setVisible(true);
                dispose();
    }//GEN-LAST:event_bgl1MousePressed

    private void bgl5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgl5MousePressed
        String ff[] = f.list();
        if (ff.length>4) {
        save = new File(pat+"\\saves\\"+savefile5);
        new Okno1().setVisible(true);
                dispose();
        } else {
            bgcreatenew.setVisible(true);
            jLabel1.setVisible(true);
            createnew.setVisible(true);
            jTextField1.setVisible(true);
        }
    }//GEN-LAST:event_bgl5MousePressed

    private void bgl2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgl2MousePressed
        String ff[] = f.list();
        if (ff.length>1) {
        save = new File(pat+"\\saves\\"+savefile2);
        new Okno1().setVisible(true);
                dispose();
        } else {
            bgcreatenew.setVisible(true);
            jLabel1.setVisible(true);
            createnew.setVisible(true);
            jTextField1.setVisible(true);
        }
    }//GEN-LAST:event_bgl2MousePressed

    private void bgl3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgl3MousePressed
        String ff[] = f.list();
        if (ff.length>2) {
        save = new File(pat+"\\saves\\"+savefile3);
        new Okno1().setVisible(true);
                dispose();
        } else {
            bgcreatenew.setVisible(true);
            jLabel1.setVisible(true);
            createnew.setVisible(true);
            jTextField1.setVisible(true);
        }
    }//GEN-LAST:event_bgl3MousePressed

    private void bgl4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgl4MousePressed
        String ff[] = f.list();
        if (ff.length>3) {
        save = new File(pat+"\\saves\\"+savefile4);
        new Okno1().setVisible(true);
                dispose();
        } else {
            bgcreatenew.setVisible(true);
            jLabel1.setVisible(true);
            createnew.setVisible(true);
            jTextField1.setVisible(true);
        }
    }//GEN-LAST:event_bgl4MousePressed

    private void bgd1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgd1MousePressed
        int n = jOptionPane1.showConfirmDialog(
            null,
            "Would you like to delete the "+savefile1+"?",
            "Delete",
            jOptionPane1.YES_NO_OPTION);

        if(true){
            sf1.delete();
            jOptionPane1.showMessageDialog(null, savefile1+" was deleted!");
        }
        else {
            jOptionPane1.showMessageDialog(null, savefile1+" was not deleted!");
        }
        try {
        String ff[] = f.list();
        if (ff.length == 1) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText("EMPTY SAVE");
        savefile2 = "";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        load2.setText("NEW");
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 2) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 3) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 4) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText(ff[3]+"");
        savefile4 = ff[3]+"";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        }
        } catch (NullPointerException e) {}
    }//GEN-LAST:event_bgd1MousePressed

    private void bgd2MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgd2MouseReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_bgd2MouseReleased

    private void bgd2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgd2MousePressed
        int n = jOptionPane1.showConfirmDialog(
            null,
            "Would you like to delete the "+savefile2+"?",
            "Delete",
            jOptionPane1.YES_NO_OPTION);

        if(true){
            sf2.delete();
            jOptionPane1.showMessageDialog(null, savefile2+" was deleted!");
        }
        else {
            jOptionPane1.showMessageDialog(null, savefile2+" was not deleted!");
        }
        try {
        String ff[] = f.list();
        if (ff.length == 1) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText("EMPTY SAVE");
        savefile2 = "";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        load2.setText("NEW");
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 2) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 3) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 4) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText(ff[3]+"");
        savefile4 = ff[3]+"";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        }
        } catch (NullPointerException e) {}
    }//GEN-LAST:event_bgd2MousePressed

    private void bgd3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgd3MousePressed
        int n = jOptionPane1.showConfirmDialog(
            null,
            "Would you like to delete the "+savefile3+"?",
            "Delete",
            jOptionPane1.YES_NO_OPTION);

        if(true){
            sf3.delete();
            jOptionPane1.showMessageDialog(null, savefile3+" was deleted!");
        }
        else {
            jOptionPane1.showMessageDialog(null, savefile3+" was not deleted!");
        }
        try {
        String ff[] = f.list();
        if (ff.length == 1) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText("EMPTY SAVE");
        savefile2 = "";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        load2.setText("NEW");
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 2) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 3) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 4) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText(ff[3]+"");
        savefile4 = ff[3]+"";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        }
        } catch (NullPointerException e) {}
    }//GEN-LAST:event_bgd3MousePressed

    private void bgd4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgd4MousePressed
        int n = jOptionPane1.showConfirmDialog(
            null,
            "Would you like to delete the "+savefile4+"?",
            "Delete",
            jOptionPane1.YES_NO_OPTION);

        if(true){
            sf4.delete();
            jOptionPane1.showMessageDialog(null, savefile4+" was deleted!");
        }
        else {
            jOptionPane1.showMessageDialog(null, savefile4+" was not deleted!");
        }
        try {
        String ff[] = f.list();
        if (ff.length == 1) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText("EMPTY SAVE");
        savefile2 = "";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        load2.setText("NEW");
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 2) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 3) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 4) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText(ff[3]+"");
        savefile4 = ff[3]+"";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        }
        } catch (NullPointerException e) {}
    }//GEN-LAST:event_bgd4MousePressed

    private void bg10MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bg10MousePressed
        int n = jOptionPane1.showConfirmDialog(
            null,
            "Would you like to delete the "+savefile5+"?",
            "Delete",
            jOptionPane1.YES_NO_OPTION);

        if(true){
            sf5.delete();
            jOptionPane1.showMessageDialog(null, savefile5+" was deleted!");
        }
        else {
            jOptionPane1.showMessageDialog(null, savefile5+" was not deleted!");
        }
        try {
        String ff[] = f.list();
        if (ff.length == 1) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText("EMPTY SAVE");
        savefile2 = "";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        load2.setText("NEW");
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 2) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText("EMPTY SAVE");
        savefile3 = "";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        load3.setText("NEW");
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 3) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText("EMPTY SAVE");
        savefile4 = "";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        load4.setText("NEW");
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        } else if (ff.length == 4) {
        file1.setText(ff[0]+"");
        savefile1 = ff[0]+"";
        sf1 = new File(pat+"\\saves\\"+savefile1);
        file2.setText(ff[1]+"");
        savefile2 = ff[1]+"";
        sf2 = new File(pat+"\\saves\\"+savefile2);
        file3.setText(ff[2]+"");
        savefile3 = ff[2]+"";
        sf3 = new File(pat+"\\saves\\"+savefile3);
        file4.setText(ff[3]+"");
        savefile4 = ff[3]+"";
        sf4 = new File(pat+"\\saves\\"+savefile4);
        file5.setText("EMPTY SAVE");
        savefile5 = "";
        sf5 = new File(pat+"\\saves\\"+savefile5);
        load5.setText("NEW");
        }
        } catch (NullPointerException e) {}
    }//GEN-LAST:event_bg10MousePressed

    private void bgcreatenewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgcreatenewMousePressed
    if (!jTextField1.getText().isEmpty()) {
        save = new File(pat+"\\saves\\"+jTextField1.getText()+".txt");
        new Okno1().setVisible(true);
        dispose();
    } else {
        
            jOptionPane1.showMessageDialog(null, "Enter a save file name!");
        
        }
    }//GEN-LAST:event_bgcreatenewMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaveFiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg10;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel bg5;
    private javax.swing.JLabel bgcreatenew;
    private javax.swing.JLabel bgd1;
    private javax.swing.JLabel bgd2;
    private javax.swing.JLabel bgd3;
    private javax.swing.JLabel bgd4;
    private javax.swing.JLabel bgl1;
    private javax.swing.JLabel bgl2;
    private javax.swing.JLabel bgl3;
    private javax.swing.JLabel bgl4;
    private javax.swing.JLabel bgl5;
    private javax.swing.JLabel createnew;
    private javax.swing.JLabel del1;
    private javax.swing.JLabel del2;
    private javax.swing.JLabel del3;
    private javax.swing.JLabel del4;
    private javax.swing.JLabel del5;
    private javax.swing.JLabel file1;
    private javax.swing.JLabel file2;
    private javax.swing.JLabel file3;
    private javax.swing.JLabel file4;
    private javax.swing.JLabel file5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel load1;
    private javax.swing.JLabel load2;
    private javax.swing.JLabel load3;
    private javax.swing.JLabel load4;
    private javax.swing.JLabel load5;
    // End of variables declaration//GEN-END:variables
}
