/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.io.File;

/**
 *
 * @author Voixy
 */
public class SaveFiles extends javax.swing.JFrame {

    /**
     * Creates new form SaveFiles
     */
    public SaveFiles() {
        initComponents();
        File f = new File("C:\\Users\\Voixy\\Documents\\NetBeansProjects\\Igra\\saves\\");
        String ff[] = f.list();
        file1.setText(ff[0]+"");
        file2.setText(ff[1]+"");
        file3.setText(ff[2]+"");
        file4.setText(ff[3]+"");
        file5.setText(ff[4]+"");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        file1 = new javax.swing.JLabel();
        file2 = new javax.swing.JLabel();
        file3 = new javax.swing.JLabel();
        file4 = new javax.swing.JLabel();
        file5 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        bg2 = new javax.swing.JLabel();
        bg3 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();
        bg5 = new javax.swing.JLabel();
        del1 = new javax.swing.JLabel();
        del2 = new javax.swing.JLabel();
        del3 = new javax.swing.JLabel();
        del4 = new javax.swing.JLabel();
        del5 = new javax.swing.JLabel();
        bgd1 = new javax.swing.JLabel();
        bgd2 = new javax.swing.JLabel();
        bgd3 = new javax.swing.JLabel();
        bgd4 = new javax.swing.JLabel();
        bg10 = new javax.swing.JLabel();
        load1 = new javax.swing.JLabel();
        load2 = new javax.swing.JLabel();
        load3 = new javax.swing.JLabel();
        load4 = new javax.swing.JLabel();
        load5 = new javax.swing.JLabel();
        bgl1 = new javax.swing.JLabel();
        bgl2 = new javax.swing.JLabel();
        bgl3 = new javax.swing.JLabel();
        bgl4 = new javax.swing.JLabel();
        bgl5 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(540, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        file1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file1.setForeground(new java.awt.Color(255, 255, 255));
        file1.setText("EMPTY SAVE");
        getContentPane().add(file1, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 82, -1, -1));

        file2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file2.setForeground(new java.awt.Color(255, 255, 255));
        file2.setText("EMPTY SAVE");
        getContentPane().add(file2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 158, -1, -1));

        file3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file3.setForeground(new java.awt.Color(255, 255, 255));
        file3.setText("EMPTY SAVE");
        getContentPane().add(file3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 230, -1, -1));

        file4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file4.setForeground(new java.awt.Color(255, 255, 255));
        file4.setText("EMPTY SAVE");
        getContentPane().add(file4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 304, -1, -1));

        file5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        file5.setForeground(new java.awt.Color(255, 255, 255));
        file5.setText("EMPTY SAVE");
        getContentPane().add(file5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 378, -1, -1));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 60, -1, -1));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 136, -1, -1));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 210, -1, -1));

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(56, 282, -1, -1));

        bg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(58, 356, -1, -1));

        del1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del1.setForeground(new java.awt.Color(255, 255, 255));
        del1.setText("DELETE");
        getContentPane().add(del1, new org.netbeans.lib.awtextra.AbsoluteConstraints(566, 74, -1, -1));

        del2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del2.setForeground(new java.awt.Color(255, 255, 255));
        del2.setText("DELETE");
        getContentPane().add(del2, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 150, -1, -1));

        del3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del3.setForeground(new java.awt.Color(255, 255, 255));
        del3.setText("DELETE");
        getContentPane().add(del3, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 222, -1, -1));

        del4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del4.setForeground(new java.awt.Color(255, 255, 255));
        del4.setText("DELETE");
        getContentPane().add(del4, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 296, -1, -1));

        del5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        del5.setForeground(new java.awt.Color(255, 255, 255));
        del5.setText("DELETE");
        getContentPane().add(del5, new org.netbeans.lib.awtextra.AbsoluteConstraints(568, 370, -1, -1));

        bgd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bgd1, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 52, -1, -1));

        bgd2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bgd2, new org.netbeans.lib.awtextra.AbsoluteConstraints(512, 128, -1, -1));

        bgd3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bgd3, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 202, -1, -1));

        bgd4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bgd4, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 274, -1, -1));

        bg10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bg10, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 348, -1, -1));

        load1.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load1.setForeground(new java.awt.Color(255, 255, 255));
        load1.setText("LOAD");
        getContentPane().add(load1, new org.netbeans.lib.awtextra.AbsoluteConstraints(354, 82, -1, -1));

        load2.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load2.setForeground(new java.awt.Color(255, 255, 255));
        load2.setText("LOAD");
        getContentPane().add(load2, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 158, -1, -1));

        load3.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load3.setForeground(new java.awt.Color(255, 255, 255));
        load3.setText("LOAD");
        getContentPane().add(load3, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 230, -1, -1));

        load4.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load4.setForeground(new java.awt.Color(255, 255, 255));
        load4.setText("LOAD");
        getContentPane().add(load4, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 304, -1, -1));

        load5.setFont(new java.awt.Font("Comic Sans MS", 0, 24)); // NOI18N
        load5.setForeground(new java.awt.Color(255, 255, 255));
        load5.setText("LOAD");
        getContentPane().add(load5, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 378, -1, -1));

        bgl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bgl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 58, -1, -1));

        bgl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bgl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 134, -1, -1));

        bgl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bgl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 208, -1, -1));

        bgl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bgl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(292, 280, -1, -1));

        bgl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        getContentPane().add(bgl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 354, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/game.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -48, 786, 642));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SaveFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SaveFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SaveFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SaveFiles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SaveFiles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg10;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel bg5;
    private javax.swing.JLabel bgd1;
    private javax.swing.JLabel bgd2;
    private javax.swing.JLabel bgd3;
    private javax.swing.JLabel bgd4;
    private javax.swing.JLabel bgl1;
    private javax.swing.JLabel bgl2;
    private javax.swing.JLabel bgl3;
    private javax.swing.JLabel bgl4;
    private javax.swing.JLabel bgl5;
    private javax.swing.JLabel del1;
    private javax.swing.JLabel del2;
    private javax.swing.JLabel del3;
    private javax.swing.JLabel del4;
    private javax.swing.JLabel del5;
    private javax.swing.JLabel file1;
    private javax.swing.JLabel file2;
    private javax.swing.JLabel file3;
    private javax.swing.JLabel file4;
    private javax.swing.JLabel file5;
    private javax.swing.JLabel load1;
    private javax.swing.JLabel load2;
    private javax.swing.JLabel load3;
    private javax.swing.JLabel load4;
    private javax.swing.JLabel load5;
    // End of variables declaration//GEN-END:variables
}
