/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author Voixy
 */
public class UvodnaStran extends javax.swing.JFrame {

    public static int s;
    public static int ns = 1;
    public static File save;
    public static File saves;
    public static int x;
    
    public UvodnaStran() {
        initComponents();
        jOptionPane1.setVisible(false);
        save = new File("C:\\Users\\Voixy\\Documents\\NetBeansProjects\\Igra\\saves\\save1.txt");
        
        saves = new File("C:\\Users\\Voixy\\Documents\\NetBeansProjects\\Igra\\saves.txt");
        jFileChooser1.setVisible(false);
        
        try {
            BufferedReader br=new BufferedReader(new FileReader(saves));
            while(br.ready()){
                if (saves.length()==0) {
                    s=1;
                } else {
                    s = Integer.parseInt(br.readLine());
                    if (s>4) {
                        ngbg.setEnabled(false);
                    }
                }
            }
        } catch (IOException ex) {
            Logger.getLogger(Okno1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jOptionPane1 = new javax.swing.JOptionPane();
        jFileChooser1 = new javax.swing.JFileChooser();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        egbg = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lgbg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ngbg = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImages(null);
        setMinimumSize(new java.awt.Dimension(960, 540));
        setPreferredSize(new java.awt.Dimension(960, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jOptionPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 430, -1, -1));

        jFileChooser1.setCurrentDirectory(new java.io.File("C:\\Users\\Voixy\\Documents\\NetBeansProjects\\Igra\\saves"));
        jFileChooser1.setDialogTitle("");
        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });
        getContentPane().add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-2, -8, -1, -1));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(182, 360, 122, -1));

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("EXIT GAME");
        jLabel3.setFocusable(false);
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(786, 360, -1, -1));

        egbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        egbg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                egbgMouseClicked(evt);
            }
        });
        getContentPane().add(egbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(738, 334, 196, -1));

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("LOAD GAME");
        jLabel2.setFocusable(false);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(574, 358, -1, -1));

        lgbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        lgbg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lgbgMouseClicked(evt);
            }
        });
        getContentPane().add(lgbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(526, 332, 196, -1));

        jLabel1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("NEW GAME");
        jLabel1.setFocusable(false);
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 356, -1, -1));

        ngbg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/—Pngtree—buttons games button illustration_5544907 (1).png"))); // NOI18N
        ngbg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ngbgMouseClicked(evt);
            }
        });
        getContentPane().add(ngbg, new org.netbeans.lib.awtextra.AbsoluteConstraints(308, 330, 196, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/start.png"))); // NOI18N
        bg.setToolTipText("");
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 2, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ngbgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ngbgMouseClicked
        if (ngbg.isEnabled()) {
        if (!jTextField1.getText().isEmpty()) {
            
                
                s++;
                    try {
                        PrintWriter pw = new PrintWriter(new FileWriter(saves,false));
                        pw.println(s);
                        pw.close();

                    } catch (IOException ex) {
                        Logger.getLogger(Okno1.class.getName()).log(Level.SEVERE, null, ex);

                    }
                save = new File("C:\\Users\\Voixy\\Documents\\NetBeansProjects\\Igra\\saves\\"+jTextField1.getText()+".txt");
                
                new Okno1().setVisible(true);
                dispose();
            
        
        } else {
        
            jOptionPane1.showMessageDialog(null, "Enter a save file name!");
        
        }
        } else {
        
            jOptionPane1.showMessageDialog(null, "You have reached the maximum amount of saves (5)! Load from a save!");
            jFileChooser1.setVisible(true);
            x = jFileChooser1.showOpenDialog(this);
        
        }
    }//GEN-LAST:event_ngbgMouseClicked

    private void lgbgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lgbgMouseClicked
        new SaveFiles().setVisible(true);
        jFileChooser1.setVisible(true);
        x = jFileChooser1.showOpenDialog(this);
    }//GEN-LAST:event_lgbgMouseClicked

    private void egbgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_egbgMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_egbgMouseClicked

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        
       
        switch (x) {
            case JFileChooser.APPROVE_OPTION:
                save = jFileChooser1.getSelectedFile();
                new Okno1().setVisible(true);
                dispose();
                break;
            case JFileChooser.CANCEL_OPTION:
                jFileChooser1.setVisible(false);
                break;
            case JFileChooser.ERROR_OPTION:
                jFileChooser1.setVisible(false);
                break; 
            default:
                break;
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UvodnaStran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UvodnaStran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UvodnaStran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UvodnaStran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UvodnaStran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JLabel egbg;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JOptionPane jOptionPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lgbg;
    private javax.swing.JLabel ngbg;
    // End of variables declaration//GEN-END:variables
}
