/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package demo;

import java.awt.FileDialog;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import java.util.*;
import java.io.*;

/**
 *
 * @author Voixy
 */
public class Okno1 extends javax.swing.JFrame implements Runnable{
    
    double score = (int) (0);
    int autoclicker = 0;
    int grandma = 0;
    int farm = 0;
    int mine = 0;
    int factory = 0;
    boolean running = true;
    boolean pause = false;
    int timer = 0;
    int autoclickerCost = 15;
    int grandmaCost = 100;
    int farmCost = 1100;
    int mineCost = 12000;
    int factoryCost = 130000;
    
    
    Thread t1;

    /**
     * Creates new form Okno1
     */
    public Okno1() {
        initComponents();
        this.setTitle(UvodnaStran.save.getName());
        jMenu2.setText("Score: "+(int) (score));
        
        try {
            BufferedReader br=new BufferedReader(new FileReader(UvodnaStran.save));
            while(br.ready()){
                score = (int) (Double.parseDouble(br.readLine()));
                jMenu2.setText("Score: "+(int) (score));
                autoclicker = Integer.parseInt(br.readLine());
                    if (autoclicker>0) jButton2.setText("AutoClicker ("+autoclicker+")");
                autoclickerCost = Integer.parseInt(br.readLine());
                    if (autoclicker>0) autoclickerCost = (int) (Math.round((15*Math.pow(1.15, autoclicker))*10)/10.0);
                jLabel1.setText(autoclickerCost+"");
                grandma = Integer.parseInt(br.readLine());
                    if (grandma>0) jButton2.setText("AutoClicker ("+grandma+")");
                grandmaCost = Integer.parseInt(br.readLine());
                    if (grandma>0) grandmaCost = (int) (Math.round((100*Math.pow(1.15, grandma))*10)/10.0);
                
            }
        } catch (IOException ex) {
            Logger.getLogger(Okno1.class.getName()).log(Level.SEVERE, null, ex);
        }
    
        jOptionPane1.setVisible(false);
        t1 = new Thread(this);
        t1.start();
        jLabel1.setText("15");
        jLabel2.setText("100");
        jLabel3.setText("1100");
        jLabel4.setText("12000");
        jLabel5.setText("130000");
        
    
}
    
    public void run() {

        //če se blnTreadIsRunning postavi na false se zanka prekine in nit se uniči
        //cas1 = System.currentTimeMillis();
        while (running == true) {

            // vsako sekundo povečaj števec za 1
            // za logiko se dejansko rabi samo števec, intSekunde je le za prikaz
            // intStevec se resetira na začetek, po vsaki periodi, da ne gre v neskonnost.           

            if (autoclicker >= 1) {
                score = Math.round((score + 0.1*autoclicker)*10)/10.0;
                jMenu2.setText("Score: "+(int) (score));
                //System.out.println(Okno1.score);
                pause = true;
            }
            
            if (grandma >= 1) {
                score = Math.round((score + 1*grandma)*10)/10.0;
                jMenu2.setText("Score: "+(int) (score));
                //System.out.println(Okno1.score);
                pause = true;
            }
            
            if (farm >= 1) {
                score = Math.round((score + 8*farm)*10)/10.0;
                jMenu2.setText("Score: "+(int) (score));
                //System.out.println(Okno1.score);
                pause = true;
            }
            
            if (mine >= 1) {
                score = Math.round((score + 47*farm)*10)/10.0;
                jMenu2.setText("Score: "+(int) (score));
                //System.out.println(Okno1.score);
                pause = true;
            }
            
            if (factory >= 1) {
                score = Math.round((score + 260*factory)*10)/10.0;
                jMenu2.setText("Score: "+(int) (score));
                //System.out.println(Okno1.score);
                pause = true;
            }
            

            // če nočemo menjati slike(pavza) nit čaka da jo spet potrebujemo
            // pavza je zmnanjšana, ker drugače ob kliku lahko čakaš celo sekundo za nadaljevanje
            
                try {
                    t1.sleep(1000);
                    //Okno1.pause = false;
                    } 
                
                catch (Exception e) {
                    //Okno1.pause = false;
                }
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        jOptionPane1 = new javax.swing.JOptionPane();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cookie = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(960, 540));
        setMinimumSize(new java.awt.Dimension(960, 540));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton2.setText("AutoClicker");
        jButton2.setFocusable(false);
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton2MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 34, 140, -1));
        getContentPane().add(jOptionPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(694, 426, -1, -1));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 34, 60, 20));

        jButton3.setText("Grandma");
        jButton3.setFocusable(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 74, 140, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 74, 60, 20));

        jButton4.setText("+10");
        jButton4.setFocusable(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 74, 110, -1));

        jButton5.setText("+10");
        jButton5.setFocusable(false);
        jButton5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jButton5MouseMoved(evt);
            }
        });
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton5MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 34, 110, -1));

        jButton6.setText("+10");
        jButton6.setFocusable(false);
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 114, 110, -1));

        jButton7.setText("Farm");
        jButton7.setFocusable(false);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton7MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 114, 140, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 114, 60, 20));
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 154, 60, 20));

        jButton8.setText("Mine");
        jButton8.setFocusable(false);
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton8MouseExited(evt);
            }
        });
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 154, 140, -1));

        jButton9.setText("+10");
        jButton9.setFocusable(false);
        jButton9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton9MouseExited(evt);
            }
        });
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 154, 110, -1));

        jButton10.setText("+10");
        jButton10.setFocusable(false);
        jButton10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton10MouseExited(evt);
            }
        });
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 194, 110, -1));

        jButton11.setText("Factory");
        jButton11.setFocusable(false);
        jButton11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton11MouseExited(evt);
            }
        });
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 194, 140, -1));
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 194, 60, 20));

        cookie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/slike/PerfectCookie (1).png"))); // NOI18N
        cookie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cookieMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                cookieMousePressed(evt);
            }
        });
        getContentPane().add(cookie, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 96, -1, -1));

        jMenu1.setText("File");

        jMenuItem2.setText("Save");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem1.setText("Start Over");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem3.setText("Exit and Save");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Score: 0.0");
        jMenu2.setFocusable(false);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        if (score >= autoclickerCost){
            score = (int) (score-autoclickerCost);
            jMenu2.setText("Score: "+(int) (score));
            autoclicker++;
            autoclickerCost = (int) (Math.round((15*Math.pow(1.15, autoclicker))*10)/10.0);
            jLabel1.setText(autoclickerCost+"");
            jButton2.setText("AutoClicker ("+autoclicker+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        
        if (score >= grandmaCost){
            score = (int) (score-grandmaCost);
            jMenu2.setText("Score: "+(int) (score));
            grandma++;
            grandmaCost = (int) (Math.round((100*Math.pow(1.15, grandma))*10)/10.0);
            jLabel2.setText(grandmaCost+"");
            jButton3.setText("Grandma ("+grandma+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (score >= ((int) (autoclickerCost*20.2303718238))){
            score = (int) (score-((int) (autoclickerCost*20.2303718238)));
            jMenu2.setText("Score: "+((int) score));
            autoclicker = autoclicker + 10;
            autoclickerCost = (int) (Math.round((100*Math.pow(1.15, autoclicker))*10)/10.0);
            jButton2.setText("AutoClicker ("+autoclicker+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (score >= ((int) (grandmaCost*20.2303718238))){
            score = (int) (score-((int) (grandmaCost*20.2303718238)));
            jMenu2.setText("Score: "+((int) score));
            grandma = grandma + 10;
            grandmaCost = (int) (Math.round((100*Math.pow(1.15, grandma))*10)/10.0);
            jButton3.setText("Grandma ("+grandma+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseMoved

    }//GEN-LAST:event_jButton5MouseMoved

    private void jButton5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseEntered
        jButton5.setText((int) (autoclickerCost*20.2303718238)+"");
    }//GEN-LAST:event_jButton5MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        jButton4.setText("+10");
    }//GEN-LAST:event_jButton4MouseExited

    private void jButton5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseExited
        jButton5.setText("+10");
    }//GEN-LAST:event_jButton5MouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        jButton4.setText((int) (grandmaCost*20.2303718238)+"");
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseEntered
        jButton2.setText(Math.round(autoclicker*0.1* 10) / 10.0+"");
    }//GEN-LAST:event_jButton2MouseEntered

    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseExited
       if (autoclicker>0) {
           jButton2.setText("AutoClicker ("+autoclicker+")");
       } else {
            jButton2.setText("AutoClicker");
       }
    }//GEN-LAST:event_jButton2MouseExited

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        jButton3.setText(grandma+"");
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        if (grandma>0) {
            jButton3.setText("Grandma ("+grandma+")");
        } else {
            jButton3.setText("Grandma");
        }
    }//GEN-LAST:event_jButton3MouseExited

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        try {
            PrintWriter pw = new PrintWriter(new FileWriter(UvodnaStran.save,false));
            pw.write("");
            pw.println(score);
            pw.println(autoclicker);
            pw.println(autoclickerCost);
            pw.println(grandma);
            pw.println(grandmaCost);
            pw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(Okno1.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        try {
            PrintWriter pw = new PrintWriter(new FileWriter(UvodnaStran.save,false));
            pw.write("");
            pw.println(score);
            pw.println(autoclicker);
            pw.println(autoclickerCost);
            pw.println(grandma);
            pw.println(grandmaCost);
            pw.flush();
            pw.close();
            
        } catch (IOException ex) {
            Logger.getLogger(Okno1.class.getName()).log(Level.SEVERE, null, ex);
        }
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(UvodnaStran.save);
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Okno1.class.getName()).log(Level.SEVERE, null, ex);
        }
        pw.write("");
        pw.flush(); 
        pw.close();
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        jButton6.setText((int) (farmCost*20.2303718238)+"");
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited
        jButton6.setText("+10");
    }//GEN-LAST:event_jButton6MouseExited

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (score >= ((int) (farmCost*20.2303718238))){
            score = (int) (score-((int) (farmCost*20.2303718238)));
            jMenu2.setText("Score: "+((int) score));
            farm = farm + 10;
            farmCost = (int) (Math.round((100*Math.pow(1.15, farm))*10)/10.0);
            jButton6.setText("Grandma ("+farm+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseEntered
        jButton7.setText(farm*8+"");
    }//GEN-LAST:event_jButton7MouseEntered

    private void jButton7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseExited
        if (farm>0) {
           jButton7.setText("Farm ("+farm+")");
       } else {
            jButton7.setText("Farm");
       }
    }//GEN-LAST:event_jButton7MouseExited

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (score >= farmCost){
            score = (int) (score-farmCost);
            jMenu2.setText("Score: "+(int) (score));
            farm++;
            farmCost = (int) (Math.round((15*Math.pow(1.15, farm))*10)/10.0);
            jLabel3.setText(farmCost+"");
            jButton7.setText("AutoClicker ("+farm+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseEntered
        jButton8.setText(mine*47+"");
    }//GEN-LAST:event_jButton8MouseEntered

    private void jButton8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseExited
        if (mine>0) {
           jButton8.setText("Mine ("+mine+")");
       } else {
            jButton8.setText("Mine");
       }
    }//GEN-LAST:event_jButton8MouseExited

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (score >= mineCost){
            score = (int) (score-mineCost);
            jMenu2.setText("Score: "+(int) (score));
            mine++;
            mineCost = (int) (Math.round((15*Math.pow(1.15, mine))*10)/10.0);
            jLabel4.setText(mineCost+"");
            jButton8.setText("AutoClicker ("+mine+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseEntered
        jButton9.setText((int) (mineCost*20.2303718238)+"");
    }//GEN-LAST:event_jButton9MouseEntered

    private void jButton9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton9MouseExited
        jButton9.setText("+10");
    }//GEN-LAST:event_jButton9MouseExited

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (score >= ((int) (mineCost*20.2303718238))){
            score = (int) (score-((int) (mineCost*20.2303718238)));
            jMenu2.setText("Score: "+((int) score));
            mine = mine + 10;
            mineCost = (int) (Math.round((100*Math.pow(1.15, mine))*10)/10.0);
            jButton9.setText("Grandma ("+mine+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseEntered
        jButton10.setText((int) (factoryCost*20.2303718238)+"");
    }//GEN-LAST:event_jButton10MouseEntered

    private void jButton10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton10MouseExited
        jButton10.setText("+10");
    }//GEN-LAST:event_jButton10MouseExited

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (score >= ((int) (factoryCost*20.2303718238))){
            score = (int) (score-((int) (factoryCost*20.2303718238)));
            jMenu2.setText("Score: "+((int) score));
            factory = factory + 10;
            factoryCost = (int) (Math.round((100*Math.pow(1.15, factory))*10)/10.0);
            jButton10.setText("Grandma ("+factory+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseEntered
        jButton11.setText(factory*260+"");
    }//GEN-LAST:event_jButton11MouseEntered

    private void jButton11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton11MouseExited
        if (factory>0) {
           jButton11.setText("Factory ("+factory+")");
       } else {
            jButton11.setText("Factory");
       }
    }//GEN-LAST:event_jButton11MouseExited

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        if (score >= factoryCost){
            score = (int) (score-factoryCost);
            jMenu2.setText("Score: "+(int) (score));
            factory++;
            factoryCost = (int) (Math.round((15*Math.pow(1.15, factory))*10)/10.0);
            jLabel5.setText(factoryCost+"");
            jButton11.setText("AutoClicker ("+factory+")");
        } else {
            jOptionPane1.showMessageDialog(null, "You don't have enough cookies!");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void cookieMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cookieMouseClicked
        
    }//GEN-LAST:event_cookieMouseClicked

    private void cookieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cookieMousePressed
        score++;
        jMenu2.setText("Score: "+(int) (score));
    }//GEN-LAST:event_cookieMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Okno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Okno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Okno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Okno1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Okno1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cookie;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JOptionPane jOptionPane1;
    // End of variables declaration//GEN-END:variables
}
